version: '3.9'

services:
  postgresql:
    container_name: postgresql
    image: 'postgres:15.5-alpine3.19'
    environment:
      POSTGRES_USER: "unleash-shopping"
      POSTGRES_PASSWORD: "swooned-bottom-glorified-gutless"
      POSTGRES_DB: "cosmetics-masculine"
    volumes:
      - /data/postgresql/data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
  nodejs:
    container_name: nodejs
    image: 'node:21.5.0-alpine3.19'
    user: node
    working_dir: /home/node/app
    command: [ "node", "server.js" ]
    environment:
      PGUSER: "cesarean-mustiness"
      PGPASSWORD: "yahoo-graduate-statue-devoutly"
      PGDATABASE: "cosmetics-masculine"
      PGHOST: postgresql
      PGPORT: 5432
    volumes:
      - /data/node/app:/home/node/app
    restart: always
    depends_on:
      - postgresql
    networks:
      - backend
  nginx:
    container_name: nginx
    image: 'nginx:1.25.3-alpine3.18'
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      - NGINX_HOST=xychelsea.tv
      - NGINX_PORT=80
    volumes:
      - /data/nginx/cache:/var/lib/nginx
      - /data/nginx/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - /data/www/xychelsea.tv/xychelsea.tv.conf:/etc/nginx/conf.d/xychelsea.tv.conf
      - /data/www/xychelsea.tv/public:/usr/share/nginx/html
      - /data/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on:
      - nodejs
    networks:
      - frontend
      - backend
  certbot:
    container_name: certbot
    image: 'certbot/certbot:arm64v8-latest'
    volumes:
      - /data/letsencrypt:/etc/letsencrypt
      - /data/www/xychelsea.tv/public/:/var/www/certbot
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
